// Generated by https://quicktype.io
export interface NasaImageItem {
  data: NasaImageDatum[];
  href: string;
  links: NasaImageItemLink[];
}

export interface NasaImageDatum {
  center: string;
  date_created: Date;
  description: string;
  keywords: string[];
  media_type: string;
  nasa_id: string;
  title: string;
}

export interface NasaImageItemLink {
  href: string;
  rel: string;
  render: string;
}
